config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  devise_for :users
  root to: "pages#home"

  resources :items do
    resources :comments, only: [:create]
  end
  resources :collections
  resources :tags, only: [:new, :create, :show]
  resources :members, only: [:new, :create, :show]
  resources :user_suggestions, only: :create
  get 'home', to: 'pages#home'
  post 'mailchimp', to: 'pages#create_mailchimp_member'
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many :item_collections
  has_many :items, through: :item_collections
  has_many_attached :photos, dependent: :destroy

  validates :label, length: { maximum: 40, too_long: "%{count} characters is the maximum allowed" }


  include PgSearch::Model

  multisearchable against: [:label, :description]
  PgSearch.multisearch_options = { using: { tsearch: { prefix: true, dictionary: "english"} } }
end

app/controllers/collections_controller.rb
require "open-uri"

class CollectionsController < ApplicationController
  before_action :set_collection, only: %i[show edit update destroy]

  def index
    if params[:query].present?
      PgSearch::Multisearch.rebuild(Collection)
      PgSearch::Multisearch.rebuild(Item)
      PgSearch::Multisearch.rebuild(Tag)
      PgSearch::Multisearch.rebuild(Member)
      pg_results = PgSearch.multisearch(params[:query])
      @results = pg_results.uniq
    else
      @collections = Collection.all.where(user: current_user)
    end
    @collection = Collection.new
  end

  def show
    @this_collection = Collection.find(params[:id])
    @items = @this_collection.items
    @collection = Collection.new
  end

  def create
    @collection = Collection.new(collection_params)
    @collection.user = current_user # Use lowercase 'collection' instead of 'Collection'
    file = URI.open(collection_params[:photo_url])
    @collection.photos.attach(io: file, filename: "photo.png", content_type: "image/png")
    if @collection.save
      redirect_to root_path, notice: 'Collection was successfully created.'
    else
      redirect_to root_path :index, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @collection.update(collection_params)
      redirect_to @collection, notice: "#{@collection.label} has been updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @collection.destroy
    redirect_to collections_url, notice: "#{collection.label} has been deleted"
  end

  private

  def set_collection
    @collection = Collection.find(params[:id])
  end

  def collection_params
    params.require(:collection).permit(:label, :description, :photo_url)
  end
end

app/views/collections/_collection.html.erb
<%= link_to collection_path(collection.searchable_id) do %>
  <div class="home-collection-card">
    <div class="home-collection-image">
      <% if collection.searchable.photos.attached? %>
        <%=cl_image_tag(collection.searchable.photos.first.key, height: 110) %>
      <% end %>
    </div>
    <div class="home-collection-title">
      <h3><%= collection.searchable.label %></h3>
    </div>
  </div>
<% end %>

app/views/collections/_item.html.erb
<%= link_to item_path(item.searchable_id) do %>
  <div class="home-collection-card">
    <div class="home-collection-image">
      <% if item.searchable.photos.attached? %>
        <%=cl_image_tag(item.searchable.photos.first.key, width: 78, height: 112, crop: :fill, format: :jpg) %>
      <% end %>
    </div>
    <div class="home-collection-title">
      <h3><%= item.searchable.title %></h3>
    </div>
  </div>
<% end %>

app/views/collections/_member.html.erb
<% member.searchable.items.each do |item| %>
  <%= link_to item_path(item) do %>
    <div class="home-collection-card">
      <div class="home-collection-image">
        <% if item.photos.attached? %>
          <%=cl_image_tag(item.photos.first.key, width: 78, height: 112, crop: :fill, format: :jpg) %>
        <% end %>
      </div>
      <div class="home-collection-title">
        <h3><%= item.title %></h3>
      </div>
    </div>
  <% end %>
<% end %>

app/views/collections/_tag.html.erb
<% tag.searchable.items.each do |item| %>
  <%= link_to item_path(item) do %>
    <div class="home-collection-card pop-on-hover">
      <div class="home-collection-image">
        <% if item.photos.attached? %>
          <%=cl_image_tag(item.photos.first.key, width: 78, height: 112, crop: :fill, format: :jpg) %>
        <% end %>
      </div>
      <div class="home-collection-title">
        <h3><%= item.title %></h3>
      </div>
    </div>
  <% end %>
<% end %>

app/views/collections/index.html.erb
<div class="screen-stretch">
  <div class="search-bar-container"> <! --div for the search bar-->
    <div class="col-sm-8">
      <%= form_with url: collections_path, method: :get, class: "d-flex align-items-center" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "search-bar",
              placeholder: "A search engine for your life"
          %>
        <%= submit_tag "Search", class: "black-primary-btn" %>
      <% end %>
    </div>
  </div>
  <% if params[:query].present? %> <!-- logic to display the collections heading / search results -->
    <div class="collections-header">
      <h2> Search Results</h2>
    </div>
  <% else %>
    <div class="collections-header">
      <h2>Collections</h2>
    </div>
  <% end %>
  <div class="all-collections-container">
    <%= link_to items_path do %> <!-- block to always display the all items collection -->
      <div class="home-collection-card-all-items pop-on-hover">
        <div class="home-collection-image">
            <%= image_tag "https://res.cloudinary.com/dp3xfbod8/image/upload/v1686854522/Stuck_at_Home_-_Brainstorming_gr6u0h.png", alt: "all items", height: 110 %>
        </div>
        <div class="home-collection-title">
          <h3>All Items</h3>
        </div>
      </div>
    <% end %>
    <% if params[:query].present? %> <!-- logic to show either all collections or search results -->
        <% if @results.empty? %>
          <div class="no-results-card">
            <h2>No results for this search, please try again</h2>
          </div>
        <% end %>
      <% @results.each do |result| %>
        <% if result.searchable_type == "Collection" %>
          <%= render "collection", collection: result %>
        <% end %>
        <% if result.searchable_type == "Item" %>
          <%= render "item", item: result %>
        <% end %>
        <% if result.searchable_type == "Member" %>
          <%= render "member", member: result %>
        <% end %>
        <% if result.searchable_type == "Tag" %>
          <%= render "tag", tag: result %>
        <% end %>
      <% end %>
    <% else %>
      <% @collections.each do |collection| %>
        <%= link_to collection_path(collection) do %>
          <div class="home-collection-card pop-on-hover">
            <div class="home-collection-image">
              <% if collection.photos.attached? %>
                <%=cl_image_tag(collection.photos.first.key, height: 110) %>
              <% end %>
            </div>
            <div class="home-collection-title">
              <h3> <%= collection.label %></h3>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <!-- Button trigger add item -->
  <div class="new-item-button">
    <%= link_to new_item_path do %>
      <button class="btn pop-on-hover">
        <svg class="plus-button" xmlns="http://www.w3.org/2000/svg" width="75" height="75" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
        </svg>
      </button>
    <% end %>
  </div>
</div>

app/views/collections/show.html.erb
<div class="screen-stretch">
  <div>
    <h1 class="text-center mt-5" ><%= @this_collection.label %></h1>
    <p  class="text-center mt-3"><%= @this_collection.description %></p>
  </div>
  <% if @items.size > 0 %>
    <div class="collections-show-items-cards">
      <% @items.each do |item|%>
        <%= link_to item_path(item) do %>
          <div class="collections-show-item-card pop-on-hover">
            <% if item.photos.attached? %>
              <div class="collections-show-image">
                <%=cl_image_tag(item.photos.first.key, format: :jpg) %>
              </div>
            <% else %>
              <div class="collections-show-image">
                <%=cl_image_tag("eb29e166f6bd2b605ac17b58a9f2f7ac_lugu4k", width: 400, height: 600, crop: :fill, format: :jpg) %>
              </div>
            <% end %>
          <div class="collections-show-item-card-info">
            <div class="collections-show-info-top">
                <h1 class="collections-show-title"><%= item.title %></h1>
                <div class="collections-show-item-card-description">
                  <%= item.description %>
                </div>
              </div>
          <!-- DATE SECTION -->
              <div class="item-show-tags-heading">
                <i class="fa-solid fa-calendar-days mx-1 mb-3"></i> <%= item.date.strftime('%Y-%m-%d') %>
              </div>

                <div class="collections-show-info-bottom">
                  <div class="collections-show-member-avatars">
                      <% item.members.each do |member| %>
                      <%# <%= member.first_name %>
                      <% if member.photos.attached? %>
                        <%=cl_image_tag(member.photos.first.key, class: "avatar") %>
                      <% end %>
                    <% end %>
                  </div>
                    <div collections-show-comments-bottom>
                      <%= item.comments.count %>
                      <i class="fa-solid fa-comment"></i>
                    </div>
                </div>

            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <div class="img-show-page">
      <img src="https://res.cloudinary.com/dp3xfbod8/image/upload/v1686759875/Tutto_Ricco_-_Home_Vacations_dh62mj.png" alt="">
    </div>
    <div>
      <p class="text-center mt-1" ><strong>Ready to add your first item?</strong></p>
    </div>
    <div class="d-flex flex-column align-items-center mt-3">
      <%= link_to "+ Add you first item", new_item_path, class: "orange-primary-btn text-decoration-none"%>
    </div>
  <% end %>
  <div class="new-item-button">
  <%= link_to new_item_path do %>
    <button class="btn pop-on-hover">
      <svg class="plus-button" xmlns="http://www.w3.org/2000/svg" width="75" height="75" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
      </svg>
    </button>
  <% end %>
  </div>
</div>