config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  devise_for :users
  root to: "pages#home"

  resources :items do
    resources :comments, only: [:create]
  end
  resources :collections
  resources :tags, only: [:new, :create, :show]
  resources :members, only: [:new, :create, :show]
  resources :user_suggestions, only: :create
  get 'home', to: 'pages#home'
  post 'mailchimp', to: 'pages#create_mailchimp_member'
end

app/views/pages/home.html.erb
<div class="container px-5">
  <div class="row my-5">
    <div class="col-12 col-lg-4 d-flex align-items-center justify-content-center">
      <div class="landing-page-opening-title my-5 d-flex flex-column text-center text-lg-start">
        <h1 class="mb-5">All your information collected in one place </h1>
        <p class="mb-5 fs-5">Find whatever you need, whenever you need it</p>
        <%= link_to "Sign up", "#newsletter", class: "text-decoration-none black-primary-btn" %>
      </div>
    </div>
    <div class="col-12 col-lg-8">
      <img class="img-fluid" src="https://res.cloudinary.com/dp3xfbod8/image/upload/v1686834012/Tutto_Ricco_-_Marching_itxym9.png" alt="" >
    </div>
  </div>

  <div class="row justify-content-center mt-5">
    <div class="col-12 col-lg-6">
      <div id="newsletter" class="newsletter-signup-container">
        <h2 class="my-5">Coming soon</h2>
        <p class="fs-5">This web application is currently in the prototype phase and will be ready for you soon. We appreciate your interest and enthusiasm.
        <p class="fs-5 mb-5">Kindly sign up below, and we'll keep you in the loop on the latest from daytm. Thanks for your patience and support!</p>

        <form class="newsletter-signup-inputs d-flex flex-column flex-sm-row justify-content-around gap-3" action="<%= mailchimp_path %>" method="post">
          <input type="email" id="email" name="email" placeholder="Email Address" required class="newsletter-signup-input-field form-control">
          <input type="submit" value="Subscribe" class="text-decoration-none black-primary-btn">
        </form>

      </div>
    </div>
  </div>

  <div class="row justify-content-center mt-5">
    <div class="col-12 col-lg-6">
      <div class="empowering-you-container my-5 text-center">
        <h2 class="my-5">Why daytm?</h2>
        <p class="fs-5">Say goodbye to the frustrations of lost and disorganized data.
          With AI powered intuitive deep tagging, search engine and life assistant, daytm will empower you
          to effortlessly and securely manage your personal and family documents.
        </p>
      </div>
    </div>
  </div>

  <div class="row align-items-center">
    <div class="col-12 col-lg-8">
      <img class="img-fluid" src="https://res.cloudinary.com/dp3xfbod8/image/upload/v1686837790/Tutto_Ricco_-_Fresh_Air_ylbk1e.png" alt="">
    </div>
    <div class="col-12 col-lg-4 d-flex flex-column align-items-center justify-content-center my-5">
      <h2 class="my-5">Expat expert</h2>
      <p class="fs-5 text-center mb-0">Life in a foreign country is complicated enough. daytm is your best friend for navigating local bureaucracy and managing your family life abroad.</p>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-12 col-lg-6 mb-5 mt-lg-5">
      <p class="fs-5 text-center mb-0">daytm is designed for busy people. Seamlessly upload, organize, tag and retrieve your data, manage expat and family life with the help of a trusted, personalized AI companion.</p>
    </div>
  </div>

</div>