config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  devise_for :users
  root to: "pages#home"

  resources :items do
    resources :comments, only: [:create]
  end
  resources :collections
  resources :tags, only: [:new, :create, :show]
  resources :members, only: [:new, :create, :show]
  resources :user_suggestions, only: :create
  get 'home', to: 'pages#home'
  post 'mailchimp', to: 'pages#create_mailchimp_member'
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :item_collections, dependent: :destroy
  has_many :collections, through: :item_collections, dependent: :destroy
  has_many :item_tags, dependent: :destroy
  has_many :tags, through: :item_tags, dependent: :destroy
  has_many :item_members, dependent: :destroy
  has_many :members, through: :item_members, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many_attached :photos, dependent: :destroy

  validates :title, length: { maximum: 40, too_long: "%{count} characters is the maximum allowed" }


  include PgSearch::Model

  multisearchable against: [:title, :description]
  PgSearch.multisearch_options = { using: { tsearch: { prefix: true, dictionary: "english"} } }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit update destroy]

  def index
    @items = Item.all.where(user: current_user)
    @collection = Collection.new
  end

  def show
    @comment = Comment.new
    @tags = Tag.all.where(user: current_user)
    @collections = Collection.all.where(user: current_user)
    @members = Member.all
    @collection = Collection.new
  end

  def new
    @item = Item.new
    @tags = Tag.where(user: current_user)
    @tag = Tag.new
    @members = Member.where(user: current_user)
    @collection = Collection.new
    @collections = Collection.where(user: current_user)
    @member_details = @members.map do |member|
      [member.first_name, member.id]
    end
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    @tags = Tag.where(id: params[:item][:tag_ids])
    @tags.each do |tag|
      @item.tags << tag
    end
    @collections = Collection.where(id: params[:item][:collection_ids])
    @collections.each do |collection|
      @item.collections << collection
    end
    if @item.save
      members = params[:item][:member_ids].map do |id|
        next if id.to_i == 0
        Member.find(id.to_i)
      end
      # tags = params.map do |id|
      #   next if id.to_i == 0
      #   Tag.find(id.to_i)
      # end

      # collections = params[:item][:collection_ids].map do |id|
      #   next if id.to_i == 0
      #   Collection.find(id.to_i)
      # end
      @item.members.push(members.compact)
      # @item.tags.push(tags.compact)
      # @item.collections.push(collections.compact)
      redirect_to @item, notice: "#{@item.title} has been successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @tags = Tag.where(user: current_user)
    @members = Member.where(user: current_user)
    @collections = Collection.where(user: current_user)
    @member_details = @members.map do |member|
      [member.first_name, member.id]
    end

  end

  def update
    @item.tags.destroy_all
    @item.members.destroy_all
    @item.collections.destroy_all
    @item.update(item_params)
    @item.user = current_user
    if @item.save
      members = params[:item][:member_ids].map do |id|
        next if id.to_i == 0
        Member.find(id.to_i)
      end
      tags = params[:item][:tag_ids].map do |id|
        next if id.to_i == 0
        Tag.find(id.to_i)
      end
      collections = params[:item][:collection_ids].map do |id|
        next if id.to_i == 0
        Collection.find(id.to_i)
      end
      @item.members.push(members.compact)
      @item.tags.push(tags.compact)
      @item.collections.push(collections.compact)
      # respond_to do |format|
      redirect_to @item, notice: "#{@item.title} has been successfully updated."
      #   format.text { render }
      # end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @item.destroy
    redirect_to items_url, notice: "#{@item.title} has been succefully destroyed."
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :description, :format, :date, :tag_ids, :member_ids, photos: [])
  end
end

app/views/items/_comment.html.erb
<p><span><%= comment.time.strftime("%-m %b at %R") %></span></p>
<p><%= comment.content %></p>

app/views/items/_item_card.html.erb
<%= link_to item_path(item) do %>
  <div class="collections-show-item-card">
    <% if item.photos.attached? %>
      <div class="collections-show-image">
        <%=cl_image_tag(item.photos.first.key, format: :jpg) %>
      </div>
    <% else %>
      <div class="collections-show-image">
        <%=cl_image_tag("eb29e166f6bd2b605ac17b58a9f2f7ac_lugu4k", width: 400, height: 600, crop: :fill, format: :jpg) %>
      </div>
    <% end %>
    <div class="collections-show-item-card-info">
      <div class="collections-show-info-top">
        <h1 class="collections-show-title"><%= item.title %></h1>
        <div class="collections-show-item-card-description">
          <%= item.description %>
          <div class="item-show-tags-heading">
            <i class="fa-solid fa-calendar-days mx-1 mb-3"></i> <%= item.date.strftime('%Y-%m-%d') %>
          </div>
        </div>
      </div>

      <div class="collections-show-info-bottom">
        <div class="collections-show-member-avatars">
          <% item.members.each do |member| %>
            <%# <%= member.first_name %>
            <% if member.photos.attached? %>
              <%=cl_image_tag(member.photos.first.key, class: "avatar") %>
            <% end %>
          <% end %>
        </div>
        <div collections-show-comments-bottom>
          <%= item.comments.count %>
          <i class="fa-solid fa-comment"></i>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="edit-form-container screen-stretch">
  <%= simple_form_for(@item) do |f| %>

    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :format %>
      <%= f.input :date, html5: true %>
      <%= f.input :description %>
      <%= f.association :members, collection: @members, label_method: :full_name, as: :check_boxes %>
      <%= f.association :tags, collection: @tags, as: :check_boxes %>

    </div>

    <div class="form-actions">
        <%= f.button :submit, "Save" %>
    </div>
  <% end %>
      <%= link_to "Back to collections", root_path %>
  </div>
</div>

app/views/items/index.html.erb
<div class="screen-stretch">
  <div>
    <h1 class="text-center mt-5" > All Items</h1>
  </div>
  <% if @items.size > 0 %>
    <div class="collections-show-items-cards">
      <% @items.each do |item|%>
        <%= link_to item_path(item) do %>
          <div class="collections-show-item-card pop-on-hover">
            <% if item.photos.attached? %>
              <div class="collections-show-image">
                <%=cl_image_tag(item.photos.first.key, format: :jpg) %>
              </div>
            <% else %>
              <div class="collections-show-image">
                <%=cl_image_tag("eb29e166f6bd2b605ac17b58a9f2f7ac_lugu4k", width: 400, height: 600, crop: :fill, format: :jpg) %>
              </div>
            <% end %>
          <div class="collections-show-item-card-info">
            <div class="collections-show-info-top">
                <h1 class="collections-show-title"><%= item.title %></h1>
                <div class="collections-show-item-card-description">
                  <%= item.description %>
                </div>
              </div>
          <!-- DATE SECTION -->
              <div class="item-show-tags-heading">
                <i class="fa-solid fa-calendar-days mx-1 mb-3"></i> <%= item.date.strftime('%Y-%m-%d') %>
              </div>

                <div class="collections-show-info-bottom">
                  <div class="collections-show-member-avatars">
                      <% item.members.each do |member| %>
                      <%# <%= member.first_name %>
                      <% if member.photos.attached? %>
                        <%=cl_image_tag(member.photos.first.key, class: "avatar") %>
                      <% end %>
                    <% end %>
                  </div>
                    <div collections-show-comments-bottom>
                      <%= item.comments.count %>
                      <i class="fa-solid fa-comment"></i>
                    </div>
                </div>

            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <div class="img-show-page">
      <img src="https://res.cloudinary.com/dp3xfbod8/image/upload/v1686759875/Tutto_Ricco_-_Home_Vacations_dh62mj.png" alt="">
    </div>
    <div>
      <p class="text-center mt-1" ><strong>Ready to add your first item?</strong></p>
    </div>
    <div class="d-flex flex-column align-items-center mt-3">
      <%= link_to "+ Add you first item", new_item_path, class: "orange-primary-btn text-decoration-none"%>
    </div>
  <% end %>
  <div class="new-item-button">
  <%= link_to new_item_path do %>
    <button class="btn pop-on-hover">
      <svg class="plus-button" xmlns="http://www.w3.org/2000/svg" width="75" height="75" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
      </svg>
    </button>
  <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="new-item-container screen-stretch">
  <div class="new-item-form-container">
    <h1>Add New Item</h1>
    <%= simple_form_for(@item) do |f| %>
      <div class="new-item-form-inputs-container">
        <div class="new-item-form-photos d-flex flex-column justify-content-around">
          <%= f.input :photos, as: :file, input_html: { multiple: true, class: 'photo-drag'  }, label: "Drag & drop your photo here"%>
          <img src="https://res.cloudinary.com/dp3xfbod8/image/upload/v1686663848/Small_file_for_new_item_ibp8wd.png" alt="" >
        </div>
        <div class="new-item-form-inputs">
          <%= f.input :title %>
          <div class="new-item-form-tags">
            <div class="new-item-form-tag-collection">
              <%= f.association :tags,
                  collection: Tag.all,
                  input_html: {multiple: true, data: {controller: "tom-select"}},
                  include_hidden: false
                  %>
            </div>
            <div class="new-tag-modal">  <!-- Button trigger modal -->
            <p>Don't see your tag? </p>
              <button type="button" class="blue-hollow-btn" data-bs-toggle="modal" data-bs-target="#exampleModal">
                <p>Create Tag</p>
              </button>
            </div>
          </div>
          <%= f.input :date, html5: true, label: "Item date", as: :date, input_html: { placeholder: 'YYYY-MM-DD' }%>
          <%= f.input :description %>
          <%= f.association :members, collection: @members, label_method: :first_name, as: :check_boxes %>
          <%= f.association :collections,
              collection: Collection.all,
              label_method: :label,
              input_html: {multiple: true, data: {controller: "tom-select"}},
              include_hidden: false
              %>
          <div class= "text-center mt-3 w-100">
            <%= f.button :submit, "Save", class: "black-primary-btn w-100" %>
          </div>
        </div>
      </div>
    <% end %>
    <!-- Button trigger modal -->
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content rounded-5">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Add new tag</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <%= simple_form_for(@tag) do |f| %>
            <%= f.input :name %>
            <%= f.button :submit, "Create Tag", class: "blue-secondary-btn w-100 my-3" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="item-show-container screen-stretch" data-controller="edit-item">
  <div class="item-show-card" data-edit-item-target="card">
    <div class="item-show-image d-flex align-items-center">
      <% if @item.photos.first %>
        <%=cl_image_tag(@item.photos.first.key, width: 400, height: 600, crop: :fill, format: :jpg) %>
      <% else %>
        <% end %>
    </div>
    <div class="item-show-content">
    <!-- EDIT AND DELETE BUTTONS -->
    <div class="item-show-edit-delete">
      <i class="fa-solid fa-pen fa-xs", data-action="click->edit-item#revealForm"></i>
      <%= link_to item_path(@item), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
        <i class="fa-solid fa-trash-can"></i>
      <% end %>
    </div>
    <div class="item-show-infos-section">
      <div class="item-show-title">
          <h1><%= @item.title %></h1>
      </div>
    <!-- DATE SECTION -->
      <div class="item-show-tags-heading">
        <i class="fa-solid fa-calendar-days mx-1 mb-3"></i> <%= @item.date.strftime('%Y-%m-%d') %>
      </div>
    <!-- DESCRIPTION SECTION -->
        <div class="item-show-description">
          <p><%= @item.description %></p>
        </div>
      </div>
    <!-- TAGS SECTION -->
      <div class="item-show-tags-section">
        <div class="item-show-tags-heading">
          <p>Tags:</p>
        </div>
        <div class="item-show-tags">
          <% @item.tags.each do |tag|%>
            <div class="item-show-tag">
              <p><%= link_to tag.name, tag_path(tag), style: "text-decoration:none; color:black;" %></p>
            </div>
          <% end %>
        </div>
      </div>
    <!-- MEMBERS SECTION -->
      <div class="item-show-members">
        <p>Members:</p>
          <div class="d-flex">
            <% @item.members.each do |member| %>
              <div class="item-member-avatar">

                  <%= link_to member_path(member) do %>
                     <% if member.photos.attached? %>
                      <%= cl_image_tag(member.photos.first.key, class: "avatar") %>
                    <% else %>
                      <img src="https://res.cloudinary.com/dp3xfbod8/image/upload/v1686759875/Tutto_Ricco_-_Home_Vacations_dh62mj.png" alt="">
                    <% end %>
                  <% end %>

              </div>
            <% end %>
          </div>
      </div>
    <!-- COMMENTS/NOTES SECTION -->
      <div class="item-show-comments-section" id="comment-container" data-controller="insert-comment">
        <p class="item-show-comment-wording"><%= @item.comments.count %> Notes:</p>
        <div class="item-show-comments" data-insert-comment-target="comments">
          <div class="item-show-comments-inner">
            <% @item.comments.each do |comment| %>
              <div class="item-show-comment">
                <%= render 'items/comment', comment: comment %>
              </div>
            <% end %>
          </div>
        </div>
        <%= simple_form_for([@item, @comment], data: { behavior: "submit-on-enter" }) do |f| %>
          <%= f.input :content, label: false, class: "test", placeholder: "What do you want to remember about this item?" %>
        <% end %>
      </div>
    </div>
  </div>
<!-- EDIT ITEM MODAL -->
  <div data-edit-item-target="form" class="d-none edit-item-container">
    <%= simple_form_for(@item) do |f| %>
      <%= f.input :title %>
        <%= f.input :date, html5: true, label: "Item date", as: :date, input_html: { placeholder: 'YYYY-MM-DD' }%>
      <%= f.input :description %>
      <%= f.association :members, collection: @members, label_method: :full_name, as: :check_boxes %>
      <%= f.association :collections,
            collection: Collection.all,
            label_method: :label,
            input_html: {multiple: true, data: {controller: "tom-select"}},
            include_hidden: false
            %>
      <%= f.association :tags,
                collection: Tag.all,
                input_html: {multiple: true, data: {controller: "tom-select"}},
                include_hidden: false
                %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.button :submit, "Update item" %>
    <% end %>
  </div>
</div>